### PR TITLE
Feat: fund depositor bot vote item

### PR DESCRIPTION
**Pull request by TheDZhon**
```python
"31) Fund Gas Funder multisig 0x5181d5D56Af4f823b96FE05f062D7a09761a5a53 for deposits with 50 stETH"
```

### CODE REVIEW

**Review by kadmil — APPROVED** [review]
LGTM

**Review by bulbozaur — APPROVED** [review]

**Review by avsetsin — APPROVED** [review]
LGTM

**Comment by TheDZhon** [comment]
**NB:** Won't be merged till the rationale research post published

**Comment by TheDZhon** [comment]
https://research.lido.fi/t/gas-funding-request/4571

**Pull request merged**
